from typing import Protocol, Callable, Optional, Awaitable

class BleGattLink(Protocol):
    async def connect(self, device_id: str) -> None: ...
    async def disconnect(self) -> None: ...
    async def write_rx(self, data: bytes) -> None: ...  # write-with-response
    def on_tx_notify(self, cb: Callable[[bytes], None]) -> None: ...
    async def start_notify(self) -> None: ...
    async def get_mtu_hint(self) -> Optional[int]: ...
